# .github/workflows/publish.yml
name: Publish to pub.dev

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+*' # tag pattern on pub.dev: 'v{{version}'

# Publish using custom workflow
jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - name: Install dependencies
        run: dart pub get
      # Here you can insert custom steps you need
      # - run: dart tool/generate-code.dart
      - name: Publish
        run: dart pub publish --force

# name: Publish Package

# on:
#   push:
#     tags:
#       - 'v[0-9]+.[0-9]+.[0-9]+*'
#     branches:
#       - main
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     environment: 'pub.dev'

#     steps:
#       - uses: actions/checkout@v3
#       - name: Install Flutter
#         uses: subosito/flutter-action@v2
#         with:
#           flutter-version: '3.24.0' 
#           channel: 'stable'

#       - name: Install dependencies
#         run: flutter pub get

#       - name: Analyze
#         run: flutter analyze

      
#       - name: Setup Pub Credentials
#         shell: bash
#         env:
#           PUB_DEV_PUBLISH_ACCESS_TOKEN: ${{ secrets.PUB_DEV_PUBLISH_ACCESS_TOKEN }}
#           PUB_DEV_PUBLISH_REFRESH_TOKEN: ${{ secrets.PUB_DEV_PUBLISH_REFRESH_TOKEN }}
#           PUB_DEV_PUBLISH_TOKEN_ENDPOINT: ${{ secrets.PUB_DEV_PUBLISH_TOKEN_ENDPOINT }}
#           PUB_DEV_PUBLISH_ID_TOKEN: ${{ secrets.PUB_DEV_PUBLISH_ID_TOKEN }}
#           PUB_DEV_PUBLISH_EXPIRATION: ${{ secrets.PUB_DEV_PUBLISH_EXPIRATION }}
#         run: |
#           sh ./pub_login.sh

#       - name: Check Publish Warnings
#         run: dart pub publish --dry-run

#       - name: Publish Package
#         run: dart pub publish -f
          

        